### ISSUE TITLE
sensors mapping

### ISSUE THREAD

**Issue by nicolalopatriello** [cyrillef/Pier9.IoT#1]
Hi, good project. I have a question. There is a way to map an IFC model with external sensors. I explain, i need to define sensors inseide ifc model, load it in viewer and then map sensors in ifc model with real sensors (es. raspberry) in build. How can i do this?

Thanks a lot!

**Comment by cyrillef** [comment]
Exactly the same way it is done here. 
If you look into https://github.com/cyrillef/Pier9.IoT/blob/master/www/data/poi-reduced.json
you'll notice there is a dbId
"sensors": {
			"id": "",
			"dbid": 3184,
which represent the ID of the object associated the sensor in the scene. RCT, IDC, or any other format do not make any difference.
